
on: [push]

env: 
   FILE_NAME : helloworld.py
jobs:
   run_script:
   
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2.3.4
       
        - name: Setup Python environment
          uses: actions/setup-python@2.2.1                 
      
        - name: Run code
          run:  python ${{env.FILE_NAME}}
   
   build_image:
                
      runs-on: ubuntu-latest
      needs: [run_script]
      steps:
        - name: Checkout repo
          uses: actions/checkout@v1
          
        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v2.2.3
          with: 
             path: ./${{env.FILE_NAME}}



         




