
on: [push]

env: 
        FILE_NAME : helloworld.py
jobs:
        run_script:
                runs-on: ubuntu-latest
                steps:
                        -name: Checkout repo
                         uses: actions/checkout@v1
                        -name: Setup Python environment
                         uses: actions/setup-python@v1.1.1
                        -name: Run code
                        -run:  python ${{env.FILE_NAME}}
        build_image:
                
                runs on: ubuntu-latest
                needs: [run_script]
                steps:
                        -name: Checkout repo
                         uses: actions/checkout@v1
                        -name: Upload artifact 
                         uses: acttions/upload-artifact@V1.0.0
                         with:
                                 name: linux
                                 path: ./${{env.FILE_NAME}}



         




